# -*- coding: utf-8 -*-
"""Drugs_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0MTuoV7-ZOpmyBhQeFCSz7CccAXlBOy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df= pd.read_csv('Drugs_Data.csv')

df.head()

df.info()

df.describe()

df.shape

df.duplicated().sum()

df.drop('Unnamed: 32' ,axis =1 , inplace = True)
df.drop('id' ,axis =1 , inplace = True)

df.head()

df['diagnosis'].value_counts()

diagnosis_mapper = {'M': 1, 'B': 0}
df['diagnosis'] = df['diagnosis'].map(diagnosis_mapper)

df.head()

x=df.drop('diagnosis',axis=1)
y=df['diagnosis']

x.head()

y.head()

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42 )

model = LogisticRegression()
model.fit(x_train,y_train)

y_pred =model.predict(x_test)

y_pred

cm = confusion_matrix(y_test,y_pred)
cm

sns.heatmap(cm,annot=True)

print(classification_report(y_test,y_pred))

